; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses release notes, you must set FAMISTUDIO_USE_RELEASE_NOTES = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Volume slides are used, you must set FAMISTUDIO_USE_VOLUME_SLIDES = 1.
; Fine pitch track is used, you must set FAMISTUDIO_USE_PITCH_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Vibrato effect is used, you must set FAMISTUDIO_USE_VIBRATO = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_undertale=music_data_undertale
.endif

music_data_undertale:
	.byte 6
	.word @instruments
	.word @samples-4
; 00 : Once upon a time
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Your Best Friend
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Fallen Down
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 03 : Enemy Approching
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 04 : Metal Crusher
	.word @song4ch0
	.word @song4ch1
	.word @song4ch2
	.word @song4ch3
	.word @song4ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 05 : Ruins
	.word @song5ch0
	.word @song5ch1
	.word @song5ch2
	.word @song5ch3
	.word @song5ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_undertale
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env9,@env16,@env2,@env0 ; 00 : Duty 210
	.word @env25,@env16,@env2,@env0 ; 01 : Duty 210 volume low
	.word @env5,@env16,@env18,@env0 ; 02 : Cymbals
	.word @env25,@env16,@env23,@env0 ; 03 : Mtt
	.word @env7,@env16,@env18,@env30 ; 04 : Kicks
	.word @env7,@env16,@env18,@env12 ; 05 : Snare
	.word @env31,@env16,@env18,@env0 ; 06 : Echo
	.word @env9,@env16,@env18,@env0 ; 07 : Basic
	.word @env9,@env16,@env28,@env0 ; 08 : Duty 012
	.word @env29,@env3,@env18,@env0 ; 09 : Crash
	.word @env25,@env16,@env28,@env0 ; 0a : Duty 012 volume low
	.word @env8,@env16,@env23,@env0 ; 0b : Lead
	.word @env21,@env16,@env20,@env6 ; 0c : Vibrate low vol
	.word @env15,@env16,@env18,@env0 ; 0d : Lead wavy
	.word @env9,@env16,@env18,@env24 ; 0e : Vibrate
	.word @env17,@env16,@env4,@env22 ; 0f : Flowey
	.word @env5,@env16,@env18,@env0 ; 10 : OUATKicks
	.word @env11,@env16,@env18,@env19 ; 11 : Fade
	.word @env1,@env26,@env18,@env13 ; 12 : Fade vibrate

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $04,$cf,$00,$01,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$12
@env2:
	.byte $c2,$c2,$c1,$c1,$c0,$00,$04
@env3:
	.byte $b0,$b3,$b6,$b8,$ba,$bc,$bf,$02,$c0,$00,$08
@env4:
	.byte $c0,$c0,$c1,$00,$02
@env5:
	.byte $00,$c8,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env6:
	.byte $00,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$00,$01
@env7:
	.byte $00,$cf,$cd,$cb,$c9,$c6,$c4,$c2,$c0,$00,$08
@env8:
	.byte $0e,$cf,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$00,$0b,$c3,$05,$c2,$06,$c1,$06,$c1,$00,$14
@env9:
	.byte $00,$cf,$7f,$00,$02
@env10:
	.byte $00,$c0,$bf,$be,$bf,$c0,$c1,$c2,$c1,$00,$01
@env11:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env12:
	.byte $00,$c1,$c3,$c8,$cc,$cf,$d3,$d6,$dc,$00,$08
@env13:
	.byte $00,$c4,$c2,$c0,$00,$03
@env14:
	.byte $00,$c0,$bf,$bf,$be,$02,$bf,$bf,$c0,$c1,$c1,$c2,$02,$c1,$c1,$00,$01
@env15:
	.byte $0c,$c2,$c4,$c6,$c7,$c8,$c9,$ca,$02,$c9,$00,$05,$c7,$c5,$c4,$c3,$c2,$00,$10
@env16:
	.byte $c0,$7f,$00,$01
@env17:
	.byte $00,$cf,$08,$ce,$07,$c0,$00,$05
@env18:
	.byte $7f,$00,$00
@env19:
	.byte $00,$bd,$be,$bf,$be,$bf,$c0,$00,$06
@env20:
	.byte $c2,$7f,$00,$00
@env21:
	.byte $00,$ca,$c7,$c5,$c3,$00,$04
@env22:
	.byte $00,$c2,$c1,$bd,$bf,$c0,$00,$05
@env23:
	.byte $c1,$7f,$00,$00
@env24:
	.byte $00,$c0,$c2,$c3,$c2,$c0,$be,$bd,$be,$00,$01
@env25:
	.byte $00,$c8,$7f,$00,$02
@env26:
	.byte $c0,$c1,$00,$00
@env27:
	.byte $00,$c0,$bd,$bc,$bd,$c0,$c3,$c4,$c3,$00,$01
@env28:
	.byte $c0,$c0,$c1,$c1,$c2,$00,$04
@env29:
	.byte $00,$ce,$ce,$cd,$cd,$cc,$cb,$ca,$02,$c9,$c8,$02,$c7,$c6,$c6,$c5,$c4,$02,$c3,$c2,$c1,$c0,$00,$15
@env30:
	.byte $00,$bb,$b1,$a9,$9f,$97,$91,$8e,$8d,$00,$08
@env31:
	.byte $00,$cf,$06,$c0,$c0,$c8,$05,$c0,$c0,$c4,$04,$c0,$c0,$c2,$04,$c0,$c0,$c1,$00,$11

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $96
@song0ref2:
	.byte $25, $eb, $31, $eb, $48, $2c, $eb, $00, $eb, $48, $2a, $eb, $31, $eb, $48, $25, $eb, $00, $eb, $48, $25, $eb, $2a, $eb
	.byte $48, $31, $eb, $33, $eb, $48, $31, $eb, $2c, $eb, $48, $2a, $eb, $00, $eb, $48
	.byte $41, $1f
	.word @song0ref2
	.byte $d1, $4f, $01, $9a, $17, $8b, $18, $89
@song0ref53:
	.byte $48, $19, $a7, $00, $8b, $7a, $19, $99, $45, $97, $7f, $25, $99, $45, $99, $22, $99, $45, $97, $48, $20, $99, $45, $99
	.byte $1e, $b3, $1d, $b5, $1e, $b3, $48, $20, $b5, $45, $b3, $29, $d1, $28, $8b, $27, $89, $48, $25, $ff, $a3, $45, $b3, $48
	.byte $1b, $a7, $00, $8b, $7c, $1b, $8b, $00, $8b, $78, $1b, $8b, $00, $89, $7f, $25, $a7, $45, $8b, $22, $a7, $45, $89, $48
	.byte $20, $a7, $45, $8b, $1e, $b3, $20, $b5, $22, $b3, $48, $1d, $b5, $45, $b3, $20, $b7, $45, $b1, $48, $20, $b5, $1e, $b3
	.byte $1d, $b5, $1e, $b3
	.byte $41, $57
	.word @song0ref53
	.byte $48, $4f, $00, $a2
@song0ref160:
	.byte $31, $99, $76, $31, $99, $7f, $2a, $99, $76, $2a, $97, $7f, $2c, $99, $76, $2c, $99, $7f, $2a, $99, $76, $2a, $97, $48
	.byte $7f, $24, $99, $76, $24, $99, $7f, $2a, $99, $76, $2a, $97, $7f, $2c, $99, $76, $2c, $99, $7f, $2a, $99, $76, $2a, $97
	.byte $48, $7f, $23, $99, $76, $23, $99, $7f, $2a, $99, $76, $2a, $97, $7f, $2c, $99, $76, $2c, $99, $7f, $2f, $99, $76, $2f
	.byte $97, $48, $7f, $2e, $99, $76, $2e, $99, $7f, $2c, $99, $76, $2c, $97, $7f, $2a, $99, $76, $2a, $99, $7f, $25, $99, $76
	.byte $25, $97, $48, $7f, $4f, $00
	.byte $41, $40
	.word @song0ref160
	.byte $48, $7f, $31, $99, $76, $31, $99, $7f, $2a, $99, $76, $2a, $97, $7e, $2c, $99, $76, $2c, $99, $7e, $2a, $99, $76, $2a
	.byte $97, $48, $7d, $24, $99, $76, $24, $99, $7d, $2a, $99, $76, $2a, $97, $7c, $2c, $99, $75, $2c, $99, $7c, $2a, $99, $75
	.byte $2a, $97, $48, $7b, $23, $99, $75, $23, $99, $7b, $2a, $99, $75, $2a, $97, $7a, $2c, $99, $74, $2c, $99, $7a, $2f, $99
	.byte $74, $2f, $97, $48, $79, $2e, $99, $74, $2e, $99, $79, $2c, $99, $74, $2c, $97, $78, $2a, $99, $73, $2a, $99, $78, $25
	.byte $99, $73, $25, $97, $48, $77, $31, $99, $73, $31, $99, $77, $2a, $99, $73, $2a, $97, $76, $2c, $99, $72, $2c, $99, $76
	.byte $2a, $99, $72, $2a, $97, $48, $75, $24, $99, $72, $24, $99, $75, $2a, $99, $72, $2a, $97, $74, $2c, $99, $71, $2c, $99
	.byte $74, $2a, $99, $71, $2a, $97, $48, $73, $23, $99, $71, $23, $99, $73, $2a, $99, $71, $2a, $97, $72, $2c, $99, $00, $99
	.byte $2f, $99, $00, $97, $48, $71, $2e, $99, $00, $99, $2c, $99, $00, $b3, $7f, $d1, $44, $00
@song0ch1:
@song0ref452:
	.byte $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db
	.byte $41, $10
	.word @song0ref452
	.byte $98
@song0ref472:
	.byte $0b, $b5, $12, $b3, $14, $b5, $12, $b3, $0b
@song0ref481:
	.byte $b5, $12, $b3, $14, $b5, $12, $b3, $0a, $b5, $12, $b3, $14, $b5, $12, $b3, $09, $b5, $12, $b3, $14, $b5, $12, $b3, $08
	.byte $b5, $12, $b3, $14, $b5, $12, $b3, $0d
	.byte $41, $0f
	.word @song0ref481
	.byte $0f, $b5, $12, $b3, $11, $b5, $0d, $b3
	.byte $41, $29
	.word @song0ref472
	.byte $41, $0f
	.word @song0ref481
	.byte $0f, $b5, $12, $b3, $11, $b5, $0d, $b3, $00, $ff, $d9
	.byte $41, $10
	.word @song0ref452
@song0ref544:
	.byte $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $44, $00
@song0ch2:
	.byte $98
@song0ref562:
	.byte $1e, $ff, $d9, $22, $ff, $d9, $21, $ff, $d9, $20, $ff, $d9, $1e, $ff, $d9, $22, $ff, $d9, $21, $ff, $d9, $20, $ff, $a3
	.byte $00, $b3
	.byte $41, $1a
	.word @song0ref562
	.byte $17, $ff, $d9, $ff, $db
@song0ref596:
	.byte $16, $ff, $d9, $15, $ff, $d9, $14, $ff, $d9, $19, $ff, $d9, $16, $ff, $d9, $1b, $eb, $19, $eb, $17, $ff, $d9, $17, $ff
	.byte $d9
	.byte $41, $13
	.word @song0ref596
	.byte $2a, $ff, $d9, $2c, $ff, $d9, $23, $ff, $d9, $2a, $ff, $d9, $2a, $ff, $d9, $2c, $ff, $d9, $23, $ff, $d9, $2a, $ff, $d9
	.byte $00, $ff, $d9
	.byte $41, $0f
	.word @song0ref544
@song0ch3:
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $a0
@song0ref662:
	.byte $04, $8b, $00, $a7, $10, $8b, $00, $a5, $0a, $8b, $00, $dd, $04, $8b, $00, $a7, $10, $8b, $00, $a5, $0a, $8b, $00, $dd
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $10
	.word @song0ref452
	.byte $44, $00
@song0ch4:
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $44, $00
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song1ref5:
	.byte $ff, $e7, $48, $ff, $e7, $48, $ff, $e7, $48, $ff, $e7, $48
	.byte $41, $08
	.word @song1ref5
	.byte $48
	.byte $41, $08
	.word @song1ref5
	.byte $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $7f, $9e
@song1ref30:
	.byte $21, $87, $00, $87, $74, $21, $87, $00, $87, $71, $21
@song1ref41:
	.byte $87, $00, $85, $7f, $25, $89, $00, $85, $74, $25, $87, $00, $87, $71, $25
@song1ref56:
	.byte $87, $00, $85, $7f, $1c, $89, $00, $85, $74, $1c, $87, $00, $87, $71, $1c
	.byte $41, $0f
	.word @song1ref41
	.byte $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
	.byte $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
	.byte $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
	.byte $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
@song1ref102:
	.byte $7f, $23, $87, $00, $87
@song1ref107:
	.byte $74, $23, $87, $00, $87, $71, $23
@song1ref114:
	.byte $87, $00, $85, $7f, $28, $89, $00, $85, $74, $28, $87, $00, $87, $71, $28
	.byte $41, $0c
	.word @song1ref56
	.byte $41, $0c
	.word @song1ref114
	.byte $87, $00, $85, $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
@song1ref145:
	.byte $7f, $1a, $87, $00, $87, $74, $1a, $87, $00, $87, $71, $1a, $87, $00, $85, $7f
	.byte $41, $0c
	.word @song1ref30
	.byte $7f, $23, $89, $00, $85
	.byte $41, $08
	.word @song1ref107
	.byte $7f, $34, $89, $00, $85, $74, $34, $87, $00, $87, $71, $26, $87, $00, $85, $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
	.byte $41, $0c
	.word @song1ref145
	.byte $41, $0c
	.word @song1ref102
@song1ref200:
	.byte $7f, $20, $87, $00, $87, $74, $20, $87, $00, $87, $71, $20, $87, $00, $85, $7f, $2c, $89, $00, $85, $74, $2c, $87, $00
	.byte $87, $71, $2c, $87, $00, $85
	.byte $41, $0c
	.word @song1ref145
	.byte $7f, $1e, $87, $00, $87, $74, $1e, $87, $00, $87, $71, $1e, $87, $00, $85, $7f, $1c, $87, $00, $87, $74, $1c, $87, $00
	.byte $87, $71, $1c, $87, $00, $85
	.byte $41, $0c
	.word @song1ref200
	.byte $7f
	.byte $41, $0c
	.word @song1ref30
	.byte $7f, $9d, $2a, $81, $2a, $81, $2c, $2c, $81, $2d, $83, $2d, $81, $2d, $81, $2d, $81, $2d, $83, $2d, $2d, $81, $00, $e1
	.byte $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
@song1ref298:
	.byte $ff, $e7, $ff, $e7, $ff, $e7, $ff, $e7, $96
@song1ref307:
	.byte $3d, $8d, $00, $a7, $3d, $9b, $3e, $99, $40, $4c, $9b, $00, $99, $3d, $9b, $00, $99, $3e, $8d, $00, $a7, $3e, $9b, $40
	.byte $4c, $99, $3b, $9b, $00, $99, $34, $9b, $00, $99
	.byte $41, $0c
	.word @song1ref307
	.byte $40, $51, $9b, $00, $99, $40, $4e, $e3, $3e, $83, $3f, $85, $40, $4c, $9b, $00, $d3
	.byte $41, $20
	.word @song1ref307
	.byte $41, $08
	.word @song1ref307
	.byte $3b, $9b, $00, $99, $38, $9b, $00, $99, $39, $d5, $40, $4f, $85, $40, $50, $83, $40, $51, $9b, $00, $e1, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $41, $08
	.word @song1ref298
	.byte $41, $08
	.word @song1ref298
	.byte $41, $08
	.word @song1ref298
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $41, $08
	.word @song1ref298
	.byte $41, $08
	.word @song1ref298
	.byte $41, $08
	.word @song1ref298
	.byte $42
	.word @song1ch4loop
@song2ch0:
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $96
@song2ref6:
	.byte $2b, $9d, $26, $9d, $2b, $9d, $26, $9d, $2b, $9d, $26, $9d, $48, $2b, $9d, $26, $9d, $2b, $9d, $26, $9d, $2b, $9d, $26
	.byte $9d, $48, $24, $9d, $22, $9d, $26, $9d, $00, $9d, $22, $9d, $24, $9d, $48, $29, $9d, $28, $9d, $29, $9d, $2b, $9d, $28
	.byte $9d, $24, $9d, $48, $2b, $9d, $24, $9d, $2b, $9d, $24, $9d, $2b, $9d, $24, $9d, $48, $2b, $9d, $23, $9d, $2b, $9d, $24
	.byte $9d, $2c, $9d, $00, $9d, $48, $2b, $9d, $27, $9d, $2b, $9d, $27, $9d, $29, $9d, $2b, $9d, $48, $29, $9d, $00, $9d, $27
	.byte $9d, $00, $9d, $26, $9d, $00, $9d, $48
	.byte $41, $60
	.word @song2ref6
	.byte $48
	.byte $41, $60
	.word @song2ref6
	.byte $48
	.byte $41, $60
	.word @song2ref6
	.byte $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $98
@song2ref126:
	.byte $1b, $9d, $1f, $9d, $22, $9d, $1f, $9d, $22, $9d, $1f, $9d, $1b, $9d, $1f, $9d, $22, $9d, $1f, $9d, $22, $9d, $1f, $9d
	.byte $18, $9d, $1c, $9d, $1f, $9d, $1c, $9d, $1f, $9d, $1c, $9d, $18, $9d, $1c, $9d, $1f, $9d, $1c, $9d, $1f, $9d, $1c, $9d
	.byte $14, $9d, $18, $9d, $1b, $9d, $18, $9d, $1b, $9d, $18, $9d, $14, $9d, $17, $9d, $1b, $9d, $17, $9d, $1b, $9d, $17, $9d
	.byte $1b, $9d, $1f, $9d, $22, $9d, $1f, $9d, $22, $9d, $1f, $9d, $1a, $9d, $1d, $9d, $22, $9d, $1d, $9d, $22, $9d, $1d, $9d
	.byte $41, $60
	.word @song2ref126
	.byte $41, $60
	.word @song2ref126
	.byte $41, $60
	.word @song2ref126
	.byte $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
@song2ref235:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $9c
@song2ref267:
	.byte $1a, $bd, $1b, $dd, $0f, $c5, $50, $d5, $1b, $22, $95, $16, $fd, $1a, $bd, $18, $ff, $8d, $50, $0d, $24, $1f, $ad, $13
	.byte $ff, $bd, $14, $bd, $50, $e8, $20, $27, $9d, $1b, $dd, $bf, $50, $0d, $27, $23, $9d, $17, $dd, $16, $ff, $bd, $16, $bd
	.byte $14, $bd
	.byte $41, $1f
	.word @song2ref267
	.byte $0f, $ff, $bd, $ff, $00, $bd, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $41, $1f
	.word @song2ref235
	.byte $bf
	.byte $41, $1f
	.word @song2ref235
	.byte $bf, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $41, $1f
	.word @song2ref235
	.byte $bf
	.byte $41, $1f
	.word @song2ref235
	.byte $bf, $42
	.word @song2ch4loop
@song3ch0:
@song3ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song3ref5:
	.byte $9d, $78, $8c, $1c, $83, $7c, $1d, $81, $7f
@song3ref14:
	.byte $1e, $a3, $00, $91, $1e, $a5, $00, $8f, $48, $49, .lobyte(@env27), .hibyte(@env27), $1c, $a5, $00, $91, $8e, $1c, $8f
	.byte $00, $91, $1c, $a5, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $8f, $48
	.byte $41, $0d
	.word @song3ref5
	.byte $48, $49, .lobyte(@env27), .hibyte(@env27), $8e, $1d, $83, $8e, $1e, $b3, $1c, $83, $1d, $9d, $1b, $91, $19, $9f, $49
	.byte .lobyte(@env0), .hibyte(@env0), $4a, $83, $48, $4f, $02, $00, $9b, $8c, $1c, $83, $1d, $81
	.byte $41, $08
	.word @song3ref14
	.byte $48, $1c, $a5, $00, $91, $1c, $8f, $00, $91, $1c, $a5, $00, $8f, $48, $9d, $50, $ec, $28, $2a, $87, $1e, $a3, $00, $4f
	.byte $01, $87, $50, $ee, $2a, $2c, $87, $20, $a5, $00, $87, $4f, $00, $87, $48, $8e, $22, $a5, $23, $87, $00, $87, $25, $b7
	.byte $00, $a3
@song3ref133:
	.byte $48, $00, $9b
@song3ref136:
	.byte $8c, $25, $83, $26, $81, $27, $a3, $00, $91, $23, $b7, $48, $8e, $1d, $a5, $1e, $91, $1d, $a3, $1b, $91, $1d, $91, $20
	.byte $8f, $48, $00, $9b, $8c, $20, $83, $21, $81, $22, $a3, $00, $91, $23, $b7, $48, $7c, $49, .lobyte(@env27), .hibyte(@env27)
	.byte $4f, $02, $8e, $20, $a5, $8e, $27, $91, $25, $cb, $49, .lobyte(@env0), .hibyte(@env0), $4a, $00, $8d, $7f, $81, $48
	.byte $4f, $00, $9d
	.byte $41, $14
	.word @song3ref136
@song3ref205:
	.byte $1e, $8f, $48, $20, $91, $1e, $91, $1d, $91, $00
@song3ref215:
	.byte $8f, $1d, $91, $1b, $91, $19, $91, $00, $8f, $48, $17, $91, $00, $91, $1b, $91, $00, $8f, $1d, $a5, $19, $91, $16, $8f
	.byte $41, $2e
	.word @song3ref133
	.byte $41, $14
	.word @song3ref136
	.byte $41, $20
	.word @song3ref205
	.byte $48
@song3ref249:
	.byte $00, $9b, $8c
@song3ref252:
	.byte $1f, $83, $20, $81, $21, $a3, $00, $87, $1a, $83, $1b, $81, $1c, $b7, $48, $8e
@song3ref268:
	.byte $21, $a5, $25, $91, $23, $a3, $21, $91, $20, $91, $21, $8f, $48, $00, $a5, $4f, $02, $1e, $91, $1d, $8f, $1b, $91, $1e
	.byte $91, $1d, $91, $1b, $8f, $48, $49, .lobyte(@env10), .hibyte(@env10), $1d, $a5, $8e, $1e, $91, $20, $db, $49, .lobyte(@env0)
	.byte .hibyte(@env0), $4a, $81, $48, $4f, $00
	.byte $41, $10
	.word @song3ref249
	.byte $48
	.byte $41, $0d
	.word @song3ref268
@song3ref323:
	.byte $9b, $21, $83, $22, $81, $23, $a3, $00, $91, $1e, $b3, $22, $81, $48, $23, $a5, $27, $91, $25, $b7, $00, $a3, $48, $00
	.byte $9b
	.byte $41, $2f
	.word @song3ref252
	.byte $48, $4f, $00
	.byte $41, $10
	.word @song3ref249
	.byte $48
	.byte $41, $0d
	.word @song3ref268
	.byte $41, $12
	.word @song3ref323
	.byte $a3, $23, $91, $25, $91, $27, $8f, $48, $28, $a5, $2c, $91, $2a, $dd, $48, $00, $91, $2a, $91, $2a, $91, $2a, $8f, $27
	.byte $91, $27, $91, $23, $91, $00, $8f, $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $4e, $0e, $4f, $01, $a7, $a4
@song3ref405:
	.byte $16, $45, $8f, $00, $a3, $16, $45, $8f, $00, $a3, $14, $45, $8f, $00, $a5, $14, $45, $85, $00, $99, $14, $87, $45, $9b
	.byte $00, $8f, $4e, $0e, $4f, $01, $a7
	.byte $41, $0a
	.word @song3ref405
	.byte $16, $45, $a3, $00, $91, $14, $45, $a1, $00, $b7, $4e, $0e, $4f, $01, $a7
	.byte $41, $1a
	.word @song3ref405
	.byte $4e, $00, $4f, $02, $9d, $8e, $50, $c1, $1f, $23, $87, $17, $87, $50, $3f, $23, $1f, $87, $00, $8f, $4f, $01, $89, $50
	.byte $ce, $23, $27, $87, $1b, $87, $50, $32, $27, $23, $87, $00, $93, $50, $d2, $23, $2a, $8d, $1e, $b9, $20, $b7, $00, $a3
@song3ref505:
	.byte $00, $a5, $8c, $23, $a3, $00, $91, $20, $b7, $8e, $19, $a5, $1b, $91, $19, $a3, $17, $91, $19, $91, $1d, $8f, $00, $a5
	.byte $8c, $1e, $a3, $00, $91, $20, $b7, $7c, $8e, $1c, $a5, $23, $91, $22, $cb, $00, $8d, $7f, $81
	.byte $41, $12
	.word @song3ref505
	.byte $1b
	.byte $41, $09
	.word @song3ref215
@song3ref555:
	.byte $19, $91, $17, $91, $16, $91, $00, $8f, $12, $91, $00, $91, $17, $91, $00, $8f, $19, $a5, $16, $91, $12, $8f
	.byte $41, $25
	.word @song3ref505
	.byte $41, $12
	.word @song3ref505
	.byte $1b
	.byte $41, $09
	.word @song3ref215
	.byte $41, $16
	.word @song3ref555
@song3ref590:
	.byte $00, $a5, $8c
@song3ref593:
	.byte $1c, $a3, $00, $91, $19, $b7, $8e, $1c, $a5, $00, $91, $1c, $a3, $00, $b7, $a7, $12, $91, $00, $a3, $12, $91, $00, $a3
	.byte $11, $a5, $12, $91, $14, $dd
	.byte $41, $11
	.word @song3ref590
@song3ref626:
	.byte $8c, $1e, $a3, $00, $91, $19, $b7, $1e, $a5, $00, $91, $20, $b7, $00, $a3, $00, $a5
	.byte $41, $1d
	.word @song3ref593
	.byte $41, $11
	.word @song3ref590
	.byte $41, $0b
	.word @song3ref626
	.byte $a3, $00, $a5, $25, $8f, $00, $a5, $25, $91, $27, $dd, $00, $91, $27, $91, $27, $91, $27, $8f, $23, $91, $23, $91, $1e
	.byte $91, $00, $8f, $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $9c
@song3ref684:
	.byte $14, $85, $00, $89, $14, $83, $00, $8b
@song3ref692:
	.byte $14, $8d, $00, $81
@song3ref696:
	.byte $14, $83, $00, $89, $14, $87, $00, $87, $14
@song3ref705:
	.byte $8d, $00, $81, $14, $85, $00, $89, $14, $83, $00, $89, $81, $14, $8b, $00, $83
	.byte $41, $11
	.word @song3ref696
	.byte $41, $0a
	.word @song3ref705
@song3ref727:
	.byte $87, $81, $14, $85, $00, $89, $14, $85, $00, $89
	.byte $41, $13
	.word @song3ref692
@song3ref740:
	.byte $87, $14, $85, $00, $87, $0b, $91, $12, $91, $17, $91, $0b, $a3, $12, $91, $19, $9b, $00, $85
	.byte $41, $25
	.word @song3ref684
	.byte $41, $11
	.word @song3ref696
	.byte $41, $0a
	.word @song3ref705
	.byte $41, $0a
	.word @song3ref727
	.byte $41, $13
	.word @song3ref692
	.byte $41, $0b
	.word @song3ref740
	.byte $0d, $a3, $12, $91, $1a, $9b, $00, $85
	.byte $41, $20
	.word @song3ref684
@song3ref788:
	.byte $17, $91, $1e, $91, $23, $91, $19, $a3, $20, $91, $1d, $91, $25, $8f
	.byte $41, $20
	.word @song3ref684
@song3ref805:
	.byte $10, $91, $17, $91, $1d, $91, $12, $a3, $17, $91, $19, $91, $12, $8f
	.byte $41, $20
	.word @song3ref684
	.byte $41, $0e
	.word @song3ref788
@song3ref825:
	.byte $17, $8f, $00, $93, $23, $8f, $00, $19, $8d, $00, $93, $27, $8f, $00, $93, $19, $8d, $00, $17, $99, $00, $89, $27, $8f
	.byte $00, $91, $25, $8f, $00, $19, $8f, $00, $1b, $8f, $00, $12, $8d, $00
	.byte $41, $20
	.word @song3ref684
	.byte $41, $0e
	.word @song3ref788
	.byte $41, $20
	.word @song3ref684
	.byte $41, $0e
	.word @song3ref805
	.byte $41, $20
	.word @song3ref684
	.byte $41, $0e
	.word @song3ref788
	.byte $41, $26
	.word @song3ref825
	.byte $41, $20
	.word @song3ref684
	.byte $41, $20
	.word @song3ref684
@song3ref890:
	.byte $09, $91, $0b, $91, $0d, $91, $06, $8f, $09, $91, $12, $91, $10, $91, $0b, $8f, $0d, $91, $0b, $91, $0d, $91, $0b, $8f
	.byte $11, $91, $16, $91, $14, $91, $13, $8f
	.byte $41, $20
	.word @song3ref684
	.byte $41, $20
	.word @song3ref684
@song3ref928:
	.byte $16, $85, $00, $89, $16, $83, $00, $8b, $16, $8d, $00, $81, $16, $83, $00, $89, $16, $87, $00, $87, $16, $8d, $00, $81
	.byte $16, $85, $00, $89, $16, $83, $00, $89
	.byte $41, $0c
	.word @song3ref928
@song3ref963:
	.byte $18, $8f, $00, $91, $16, $91, $18, $91, $13, $8f
	.byte $41, $20
	.word @song3ref684
	.byte $41, $20
	.word @song3ref684
	.byte $41, $20
	.word @song3ref890
	.byte $41, $20
	.word @song3ref684
	.byte $41, $20
	.word @song3ref684
	.byte $41, $20
	.word @song3ref928
	.byte $41, $08
	.word @song3ref928
	.byte $1a, $91
	.byte $41, $08
	.word @song3ref963
	.byte $1a, $8f, $14, $91, $00, $91, $14, $91, $00, $dd, $93, $12, $91, $12, $91, $12, $8f, $0f, $91, $0f, $91, $0b, $91, $00
	.byte $8f, $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
	.byte $84
@song3ref1029:
	.byte $14, $87, $00, $87, $21, $87, $00, $87, $14, $87, $00, $87, $21, $87, $00, $85
	.byte $41, $10
	.word @song3ref1029
	.byte $41, $10
	.word @song3ref1029
	.byte $41, $10
	.word @song3ref1029
	.byte $41, $10
	.word @song3ref1029
	.byte $41, $10
	.word @song3ref1029
@song3ref1060:
	.byte $88, $18, $8d, $00, $81
@song3ref1065:
	.byte $84, $15, $83, $00, $81, $15, $83, $00, $81, $15, $83, $00, $8b, $88, $18, $8f, $00, $91
	.byte $41, $08
	.word @song3ref1065
	.byte $88, $18, $91, $84, $21, $87, $00, $85
	.byte $41, $10
	.word @song3ref1029
	.byte $41, $10
	.word @song3ref1029
	.byte $41, $10
	.word @song3ref1029
	.byte $41, $10
	.word @song3ref1029
	.byte $41, $10
	.word @song3ref1029
	.byte $41, $10
	.word @song3ref1029
	.byte $41, $14
	.word @song3ref1060
	.byte $84
@song3ref1116:
	.byte $16, $83, $00, $81, $16, $83, $00, $81
	.byte $41, $08
	.word @song3ref1116
	.byte $16, $83, $00, $81, $16, $81, $00, $81
@song3ref1135:
	.byte $92, $22, $b9
@song3ref1138:
	.byte $84, $14, $83, $21, $81, $00, $85, $14, $83, $21, $81, $00, $87, $14, $83, $21, $81, $00, $87, $88, $18, $91
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
@song3ref1190:
	.byte $84, $14, $83, $21, $81, $00, $85
@song3ref1197:
	.byte $16
@song3ref1198:
	.byte $1f, $85, $00, $87, $16, $1f, $85, $00, $87, $88, $19, $00, $81, $8a, $20, $8b, $88, $16, $00, $8d
	.byte $41, $0a
	.word @song3ref1197
	.byte $19, $8a, $20, $8d, $00, $88, $16, $00, $8d
	.byte $41, $0a
	.word @song3ref1197
@song3ref1233:
	.byte $19, $8a, $20, $8d, $00, $88, $16, $00, $8d, $16, $8a, $20, $8d, $00, $88, $16, $00, $8f, $19, $8a, $20, $8d, $00, $88
	.byte $16, $00, $8d
	.byte $41, $16
	.word @song3ref1135
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $18
	.word @song3ref1190
	.byte $41, $0a
	.word @song3ref1197
	.byte $41, $08
	.word @song3ref1233
	.byte $41, $09
	.word @song3ref1198
	.byte $41, $15
	.word @song3ref1233
	.byte $41, $16
	.word @song3ref1135
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $84, $14, $83, $21, $81, $00, $85
	.byte $41, $16
	.word @song3ref1135
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $84, $14, $83, $21, $81, $00, $85
	.byte $41, $16
	.word @song3ref1135
	.byte $41, $14
	.word @song3ref1138
	.byte $41, $14
	.word @song3ref1138
	.byte $84, $14, $83, $21, $81, $00, $85, $88
@song3ref1417:
	.byte $14, $87, $00, $9b, $14, $87, $00, $99
	.byte $41, $08
	.word @song3ref1417
@song3ref1428:
	.byte $14, $87, $00, $87, $14, $87, $00, $87, $14, $87, $00, $87, $14, $87, $00, $85
	.byte $41, $0b
	.word @song3ref1428
	.byte $99, $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
@song3ref1452:
	.byte $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b
	.byte $41, $08
	.word @song3ref1452
	.byte $41, $08
	.word @song3ref1452
	.byte $41, $08
	.word @song3ref1452
	.byte $41, $08
	.word @song3ref1452
	.byte $41, $08
	.word @song3ref1452
	.byte $41, $08
	.word @song3ref1452
	.byte $41, $08
	.word @song3ref1452
	.byte $41, $08
	.word @song3ref1452
	.byte $41, $08
	.word @song3ref1452
	.byte $ff, $9b, $ff, $9b, $42
	.word @song3ch4loop
@song4ch0:
@song4ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $f7, $48, $ff, $f7, $48, $7f
@song4ref12:
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a, $80
@song4ref17:
	.byte $26, $27, $28, $81, $90, $29, $8d, $00, $85, $80, $28, $87, $82, $29, $83, $80, $27, $83, $82, $28, $85, $80, $28, $87
	.byte $00, $83, $82, $27, $85, $80, $28, $85, $26, $87, $00, $83, $24, $83, $82, $26, $85, $80, $23, $87, $00, $83, $82, $24
	.byte $85, $80, $23, $85, $21, $87, $82, $23, $83, $80, $20, $83, $82, $21, $85, $80, $21, $87, $00, $83, $82, $20, $85, $21
	.byte $85, $80, $1c, $87, $82, $20, $83, $80, $1d, $83, $82, $1c, $85, $48, $80, $1c, $87, $82, $1d, $83, $80, $1d, $85, $82
	.byte $1c, $85, $80, $1c, $81, $82, $1d, $89, $80, $1b, $83, $82, $1c, $85, $80, $1c, $87, $82, $1b, $83, $80, $20, $85, $82
	.byte $1c, $85, $80, $24, $87, $82, $20, $83, $80, $23, $83, $82, $24, $85, $80, $21, $8d, $82, $23, $85, $00, $85, $80, $21
	.byte $87, $82, $21, $83, $80, $23, $83, $82, $21, $85, $80, $24, $8d, $82, $23, $85, $00, $85, $80, $23, $87, $82, $24, $83
	.byte $80, $24, $83, $82, $23, $85, $48, $80, $26, $8d, $82, $24, $85, $00, $85, $80, $24, $87, $82, $26, $83, $80, $23, $83
	.byte $82, $24, $85, $80, $20, $8d, $82, $23, $85, $00, $85, $80, $20, $87, $82, $20, $83, $80, $23, $83, $82, $20, $85, $80
	.byte $24, $8d, $82, $23, $85, $00, $85, $80, $23, $87, $82, $24, $83, $80, $21, $83, $82, $23, $85, $80, $1c, $8d, $82, $21
	.byte $85, $00, $85, $80, $1c, $87, $82, $1c, $83, $80, $1d, $83, $82, $1c, $85, $48, $80, $1c, $87, $82, $1d, $83, $80, $1b
	.byte $85, $82, $1c, $85, $80, $1c, $87, $82, $1b, $83, $80, $1d, $83, $82, $1c, $85, $80, $1c, $87, $82, $1d, $83, $80, $17
	.byte $85, $82, $1c, $85, $80, $24, $87, $82, $17, $83, $80, $23, $83, $82, $24, $85, $80, $21, $8d, $82, $23, $85, $00, $85
	.byte $80, $21, $87, $82, $21, $83, $80, $20, $83, $82, $21, $85, $80, $21, $89, $82, $20, $81, $80, $21, $81, $2b, $83, $2c
	.byte $83, $2d, $89, $82, $2b, $81, $2c, $83, $2d, $85, $48
	.byte $41, $e6
	.word @song4ref12
	.byte $80, $24, $85, $00, $85, $26, $85, $00, $85, $28, $83, $00, $85, $48, $49, .lobyte(@env14), .hibyte(@env14), $29, $d3
	.byte $00, $85, $80, $24, $93, $00, $85, $21, $d3, $00, $85, $1d, $93, $00, $85, $48, $20, $b3, $00, $85, $1c, $b3, $00, $85
	.byte $28, $b3, $00, $85, $27, $b3, $00, $85, $48, $26, $d3, $00, $85, $22, $93, $00, $85, $20, $d3, $00, $85, $1c, $93, $00
	.byte $85, $48
@song4ref436:
	.byte $21, $87, $00, $83, $20, $85, $00, $85, $21, $93, $00, $85, $23, $87, $00, $83, $21, $85, $00, $85, $23, $93, $00, $85
	.byte $24, $b3, $00, $85, $24, $87, $00, $83, $26, $85, $00, $85, $28, $87, $00, $83, $2b, $83, $00, $85, $48, $2d, $d3, $00
	.byte $85, $2b, $93, $00, $85, $29, $d3, $00, $85, $28, $93, $00, $85, $48, $27, $b3, $00, $85, $2c, $b3, $00, $85, $23, $b3
	.byte $00, $85, $28, $b3, $00, $85, $48, $26, $e3, $50, $04, $32, $31, $89, $50, $fb, $31, $32, $87, $26, $b3, $00, $85, $29
	.byte $b3, $00, $85, $48, $28, $eb, $28, $83, $28, $85, $79, $51, $fd, $00, $28, $87, $00, $83, $29, $85, $00, $85, $28, $87
	.byte $00, $83, $27, $83, $00, $85, $28, $87, $00, $83, $27, $85, $00, $85, $28, $87, $00, $83, $27, $83, $00, $85, $48, $7f
	.byte $49, .lobyte(@env0), .hibyte(@env0), $4a
	.byte $41, $f4
	.word @song4ref17
	.byte $48
	.byte $41, $e7
	.word @song4ref12
	.byte $85, $00, $a3, $48, $ff, $f7, $48, $ff, $f7, $48, $ff, $f7, $48, $ff, $f7, $42
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $ff, $f7, $ff, $f7
@song4ref614:
	.byte $78, $9a
@song4ref616:
	.byte $31, $89, $32, $89, $33, $85, $34, $89, $35, $87, $36, $85, $37, $89, $38, $89, $39, $85, $3a, $89, $3b, $87, $3c, $85
	.byte $3d, $89, $3e, $89, $3f, $85, $40, $4c, $89, $40, $4d, $87, $40, $4e, $85, $40, $4f, $89, $40, $50, $89, $40, $51, $85
	.byte $40, $52, $89, $40, $53, $87, $40, $54, $85, $40, $55, $87, $40, $54, $87, $40, $53, $89, $40, $52, $87, $40, $51, $87
	.byte $40, $50, $87, $40, $4f, $87, $40, $4e, $87, $40, $4d, $89, $40, $4c, $87, $3f, $87, $3e, $87, $3d, $87, $3c, $87, $3b
	.byte $89, $3a, $87, $39, $87, $38, $87, $37, $87, $36, $87, $35, $89, $34, $87, $33, $87, $32, $87
	.byte $41, $60
	.word @song4ref616
@song4ref734:
	.byte $7f, $00, $8d, $80, $20, $85, $00, $85, $21, $85, $00, $85, $23, $83, $00, $85, $20, $89, $00, $91, $20, $87, $00, $83
	.byte $21, $83, $00, $85, $1c, $87, $00, $83, $1b, $85, $00, $85, $1c, $87, $00, $83, $1d, $83, $00, $85, $1c, $87, $00, $83
	.byte $1b, $85, $00, $85, $17, $87, $00, $83, $15, $83, $00, $85, $17, $87, $00, $83, $15, $85, $00, $85, $17, $87, $00, $83
	.byte $18, $83, $00, $85, $17, $87, $00, $83, $15, $85, $00, $85, $17, $87, $00, $83, $1c, $83, $00, $85, $1d, $8d, $00, $8d
	.byte $1c, $87, $00, $83, $1a, $83, $00, $85, $1d, $8d, $00, $8d, $1a, $87, $00, $83, $1b, $83, $00, $85, $20, $87, $00, $83
	.byte $1c, $85, $00, $85, $17, $87, $00, $83, $1c, $83, $00, $85, $1a, $87, $00, $83, $15, $85, $00, $85, $1a, $87, $00, $83
	.byte $18, $83, $00, $85, $15, $87, $00, $83, $17, $85, $00, $85, $18, $87, $00, $83, $17, $83, $00, $85, $15, $87, $00, $83
	.byte $17, $85, $00, $85, $18, $87, $00, $83, $17, $83, $00, $85, $14, $87, $00, $83, $11, $85, $00, $85, $14, $87, $00, $83
	.byte $15, $83, $00, $85, $14, $87, $00, $83, $11, $85, $00, $85, $14, $87, $00, $83, $11, $83, $00, $85, $14, $8d, $00, $8d
	.byte $14, $87, $00, $83, $13, $83, $00, $85, $14, $89, $00, $af, $90, $21, $85, $00, $85, $1d, $81, $78, $94, $21, $89, $7f
	.byte $90, $18, $85, $78, $94, $1d, $85, $7f, $90, $15, $81, $78, $94, $18, $87, $7f, $90, $21, $85, $78, $94, $15, $85, $7f
	.byte $90, $1d, $81, $78, $94, $21, $89, $7f, $90
@song4ref1007:
	.byte $18, $85, $78, $1d, $85, $7f, $15, $81
@song4ref1015:
	.byte $78, $18, $87, $7f, $1d, $85, $78, $15, $85, $7f, $18, $81, $78, $1d, $89, $7f, $15, $85, $78, $18, $85, $7f, $11, $81
	.byte $78, $15, $87, $11, $8d, $15, $81, $11, $89, $7f, $18, $85, $15, $89
	.byte $41, $1c
	.word @song4ref1015
	.byte $78, $18, $87, $7f, $23, $85, $78, $15, $85, $7f, $20, $81, $78, $23, $89, $7f, $1c, $85, $78, $20, $85, $7f, $17, $81
	.byte $78, $1c, $87, $7f, $20, $85, $78, $17, $85, $7f, $1c, $81, $78, $20, $89, $7f, $17, $85, $78, $1c, $85, $7f, $14, $81
	.byte $78, $17, $87, $7f, $22, $85, $78, $14
@song4ref1112:
	.byte $85, $7f, $1d, $81, $78, $22, $89, $7f, $1a, $85, $78, $1d, $85, $7f, $16, $81, $78, $1a, $87, $7f, $22, $85, $78, $16
	.byte $85, $7f, $1d, $81, $78, $22, $89, $7f, $1a, $85, $78, $1d, $85, $7f, $16, $81, $78, $1a, $87, $7f, $1c, $85, $78, $16
	.byte $85, $7f, $17, $81, $78, $1c, $89, $7f, $14, $85, $78, $17, $85, $7f, $10, $81, $78, $14, $87, $7f, $1c, $85, $78, $10
	.byte $85, $7f, $17, $81, $78, $1c, $89, $7f, $14, $85, $78, $17, $85, $7f, $10, $81, $78, $14, $87
	.byte $41, $2c
	.word @song4ref436
	.byte $7f, $24, $85, $00, $85, $21, $81, $78, $24, $89, $1d, $85, $21, $85, $7f, $18, $81, $78, $1d, $87, $7f, $21, $85, $19
	.byte $78, $85, $7f, $1d, $81, $78, $21, $89, $7f, $18, $85, $78, $1d, $85, $7f, $15, $81, $78, $18, $87, $7f, $21, $85, $78
	.byte $15, $85, $7f, $1d, $81, $78, $21, $89, $7f
	.byte $41, $18
	.word @song4ref1007
	.byte $7f, $20, $85, $78, $11
@song4ref1271:
	.byte $85, $7f, $1b, $81, $78, $20, $89, $7f, $17, $85, $78, $1b, $85, $7f, $14, $81, $78, $17, $87, $7f, $10, $85, $78, $14
	.byte $85, $7f, $14, $81, $78, $10, $89, $7f, $17, $85, $78, $14, $85, $7f, $1c, $81, $78, $17, $87, $7f, $20, $85, $78, $1c
	.byte $41, $11
	.word @song4ref1271
	.byte $7f, $17, $81, $78, $10, $89, $7f, $21, $85, $78, $17, $85, $7f, $23, $81, $78, $21, $87, $7f, $22, $85, $78, $23
	.byte $41, $1d
	.word @song4ref1112
	.byte $7f, $22, $85, $78, $16
	.byte $41, $15
	.word @song4ref1112
	.byte $7f, $23, $85, $78, $1d, $85, $7f, $26, $81, $78, $23, $87, $7f, $24, $85, $78, $26, $85, $7f, $21, $81, $78, $24, $89
	.byte $7f, $1d, $85, $78, $21, $85, $7f, $18, $81, $78, $1d, $87, $7f, $21, $85, $78, $18, $85, $7f, $1d, $81, $78, $21, $89
	.byte $7f, $18, $85, $78, $1d, $85, $00, $81, $51, $fe, $20, $18, $87, $28, $85, $28, $89, $00, $81, $29, $85, $00, $85, $28
	.byte $89, $00, $27, $85, $00, $85, $28, $89, $00, $81, $27, $85, $00, $85, $28, $89, $00, $27, $85
	.byte $41, $60
	.word @song4ref614
	.byte $41, $60
	.word @song4ref616
	.byte $41, $e2
	.word @song4ref734
	.byte $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $42
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
	.byte $ff, $f7, $ff, $f7, $8e
@song4ref1473:
	.byte $30, $81, $00, $89, $1c, $85, $00, $85, $15, $89, $00, $81, $1c, $83, $00, $85, $30, $81, $00, $89, $1c, $85, $00, $85
	.byte $10, $87, $00, $83, $17, $83, $00, $85, $30, $81, $00, $89, $17, $85, $00, $85, $10, $87, $00, $83, $17, $83, $00, $85
	.byte $30, $81, $00, $89, $17, $85, $00, $85, $15, $87, $00, $83, $1c, $83, $00, $85
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $41, $40
	.word @song4ref1473
	.byte $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $42
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
	.byte $86, $1f, $a5, $00, $85, $1f, $83, $00, $85, $1d, $87, $00, $93, $1d, $87, $00, $91, $1c, $95, $00, $95, $1c, $83, $00
	.byte $85, $1a, $a5, $00, $93, $18, $91, $00, $99, $18, $83, $00, $85, $18, $87, $00, $93, $18, $85, $00, $93, $19, $bb, $00
	.byte $bb
@song4ref1659:
	.byte $88, $14, $8d, $86, $18, $85, $00, $85, $84, $20, $8d, $86, $18, $83, $00, $85, $1d, $89, $00, $81, $8a, $16, $8d, $86
	.byte $18, $87, $00, $83, $84, $20, $8b, $88, $14, $8d, $86, $19, $85, $00, $85, $84, $20, $8d, $86, $19, $83, $00, $85, $1d
	.byte $89, $00, $81, $8a, $16, $8d, $86, $19, $87, $00, $83, $84, $20, $8b
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $16
	.word @song4ref1659
@song4ref1730:
	.byte $18, $81, $00, $87, $88, $14, $8d, $86, $19, $85, $00, $85, $84, $20, $8d, $86, $19, $83, $00, $85, $1e, $89, $00, $91
	.byte $8a, $16, $8d, $00, $8b
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $16
	.word @song4ref1659
	.byte $41, $18
	.word @song4ref1730
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $86, $18, $9d, $18, $85, $00, $85, $18, $83, $00, $85, $19, $9d, $18, $87, $00, $83, $18, $81, $00, $87, $1a, $9d, $19
	.byte $89, $00, $81, $19, $83, $00, $85, $1d, $89, $00, $81, $19, $85, $00, $85, $19, $87, $00, $83, $19, $81, $00, $87
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $86, $18, $ad, $00, $8b, $18, $ad, $00, $8b, $19, $ad, $00, $c9
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $16
	.word @song4ref1659
	.byte $41, $18
	.word @song4ref1730
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $16
	.word @song4ref1659
	.byte $41, $18
	.word @song4ref1730
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $30
	.word @song4ref1659
	.byte $41, $16
	.word @song4ref1659
	.byte $41, $18
	.word @song4ref1730
	.byte $42
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
@song4ref1901:
	.byte $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7
	.byte $41, $12
	.word @song4ref1901
	.byte $41, $12
	.word @song4ref1901
	.byte $ff, $f7, $ff, $f7, $ff, $f7, $42
	.word @song4ch4loop
@song5ch0:
@song5ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $9b, $48, $ff, $9b, $48, $ff, $9b, $48, $78, $b3, $4f
	.byte $01, $8c, $2a, $97, $2b, $97, $2a, $81, $2b, $83, $2a, $81, $2b, $83, $2a, $83, $26, $97, $48
@song5ref36:
	.byte $28, $cb, $2d, $b1, $30, $97, $48, $2d, $b1, $2f, $97, $30, $97, $32, $97, $2f, $97, $48, $30, $cb, $2f, $b1, $2d, $8b
	.byte $2b, $89, $48, $2a, $b1, $30, $97, $32, $97, $34, $97, $36, $97, $48, $30, $cb, $2f, $b1, $28, $97, $48, $2d, $b1, $2b
	.byte $b1, $2a, $b1, $48, $2b, $97, $2a, $97, $28, $97, $26, $b1, $2d, $97, $48, $28, $b1, $00, $97, $23, $97, $24, $97, $23
	.byte $97, $48, $26, $e5, $00, $b1, $48, $b3, $36, $97, $37, $97, $36, $97, $37, $97, $48, $36, $cb, $39, $cb, $48, $34, $cb
	.byte $2f, $97, $30, $97, $2f, $97, $48, $32, $e5, $00, $b1, $48, $cd, $2f, $97, $30, $97, $2f, $97, $48, $32, $e5, $00, $b1
	.byte $48, $ff, $9b, $48, $7f, $4f, $02
	.byte $41, $6c
	.word @song5ref36
	.byte $48, $4f, $02
	.byte $41, $55
	.word @song5ref36
	.byte $23, $97, $24, $97, $23, $97, $48, $26, $ff, $99, $48, $00, $cb, $23, $97, $25, $97, $23, $97, $48, $26, $ff, $99, $48
	.byte $2c, $cb, $2b, $97, $29, $97, $2c, $97, $48, $24, $ff, $99, $48, $00, $b1, $23, $b1, $24, $b1, $48, $23, $cb, $24, $8b
	.byte $23, $89, $21, $97, $23, $97, $48, $2a, $e5, $26, $b1, $48, $28, $ff, $99, $48, $00, $e5, $29, $8b, $28, $89, $26, $97
	.byte $48, $28, $e5, $23, $b1, $48, $1f, $b1, $21, $b1, $23, $b1, $48, $26, $ff, $99, $48, $00, $e5, $28, $8b, $26, $89, $24
	.byte $97, $48, $26, $ff, $99, $48, $25, $ff, $99, $48, $26, $ff, $99, $48, $25, $ff, $99, $48, $2a, $ff, $99, $48, $74, $15
	.byte $b1, $00, $e5, $48, $10, $97, $17, $97, $13, $b1, $12, $97, $13, $97, $48, $15, $b1, $00, $e5, $42
	.word @song5ch0loop
@song5ch1:
@song5ch1loop:
	.byte $78, $4f, $01, $8c
@song5ref319:
	.byte $15, $97, $1c, $97, $18, $b1, $17, $97, $18, $97, $1a, $b1, $00, $cb, $13, $97, $4f, $01
	.byte $41, $0d
	.word @song5ref319
	.byte $e5, $4f, $01
	.byte $41, $10
	.word @song5ref319
	.byte $4f, $01
	.byte $41, $0d
	.word @song5ref319
	.byte $e5, $4f, $01
	.byte $41, $10
	.word @song5ref319
	.byte $4f, $01
	.byte $41, $0d
	.word @song5ref319
@song5ref362:
	.byte $97, $0e, $97, $13, $97, $10
@song5ref368:
	.byte $97, $4f, $01, $15, $97, $1c, $97, $18, $b1, $17, $97, $18, $97, $1a, $b1, $0e, $97, $15, $97, $18, $97, $17
	.byte $41, $0d
	.word @song5ref368
	.byte $12, $97, $0e, $97, $10, $97, $12
	.byte $41, $0d
	.word @song5ref368
	.byte $00, $e5, $21, $97, $28, $97, $24, $b1, $23, $97, $24, $97, $26, $b1, $00, $e5
@song5ref419:
	.byte $7f
@song5ref420:
	.byte $09, $97, $10, $97, $0c, $b1, $0b, $97, $0c, $97, $0e, $b1, $00, $97, $09, $97, $07, $97, $13, $97, $09, $97, $10, $97
	.byte $0c, $b1, $0e, $97, $10, $97, $12, $b1, $00, $b1, $12, $97, $0e, $97
	.byte $41, $22
	.word @song5ref420
	.byte $09, $97, $0e, $97, $78, $4f, $01
	.byte $41, $0d
	.word @song5ref319
	.byte $41, $13
	.word @song5ref362
	.byte $00
	.byte $41, $13
	.word @song5ref362
	.byte $00, $e5, $ff, $9b, $ff, $9b
	.byte $41, $26
	.word @song5ref419
	.byte $41, $22
	.word @song5ref420
	.byte $09, $97, $0e, $97, $78, $4f, $01
	.byte $41, $0d
	.word @song5ref319
	.byte $41, $13
	.word @song5ref362
	.byte $00, $97, $0e, $97, $13, $97, $10, $97, $7f, $0b, $97, $12, $97, $0e, $b1, $0b, $97, $12, $97, $0b, $97, $12, $97, $17
	.byte $b1, $00, $b1, $0a, $97, $11, $97, $0e, $b1, $0a, $97, $11, $97, $0a, $97, $11, $97, $14, $b1, $13, $97, $11, $97, $09
	.byte $97, $10, $97, $0c, $b1, $09, $97, $10, $97, $09, $97, $10, $97, $15, $b1, $10, $b1, $07, $97, $0b, $97, $13, $b1, $0e
	.byte $b1, $0e, $b1, $10, $b1, $12, $b1, $05, $97, $10, $97, $0c, $cb, $10, $97, $05, $b1, $10, $b1, $15, $b1, $0b, $97, $0e
	.byte $97, $0b, $cb, $0e, $97, $0b, $b1, $0e, $b1, $10, $b1, $13, $ff, $99, $00, $ff, $99
@song5ref616:
	.byte $1c, $97, $1f, $97, $23, $97, $1f, $97, $22, $97, $1e, $97, $1c, $97, $1f, $97, $23, $97, $1f, $97, $22, $97, $1e, $97
	.byte $41, $18
	.word @song5ref616
	.byte $1c, $97, $23, $97, $26, $97, $23, $97, $25, $97, $21, $97, $1c, $97, $23, $97, $26, $97, $23, $97, $25, $97, $21, $97
	.byte $00, $ff, $99, $ff, $9b, $42
	.word @song5ch1loop
@song5ch2:
@song5ch2loop:
@song5ref676:
	.byte $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $ff, $9b, $9c, $1c, $cb, $21, $b1, $24, $97, $21, $b1, $23, $97, $24, $97, $26, $97, $23, $97, $24, $cb, $23, $b1, $21
	.byte $8b, $1f, $89, $1e, $b1, $24, $97, $26, $97, $28, $97, $2a, $97, $24, $cb, $23, $b1, $1c, $97, $21, $b1, $1f, $b1, $1e
	.byte $b1, $1f, $97, $1e, $97, $1c, $97, $1a, $b1, $21, $97, $1c, $b1, $00, $97, $17, $97, $18, $97, $17, $97, $1a, $e5, $00
	.byte $b1, $ff, $9b, $ff, $9b, $cd, $17, $97, $18, $97, $17, $97, $1a, $ff, $99, $00, $cb, $17, $97, $19, $97, $17, $97, $1a
	.byte $ff, $99, $20, $cb, $1f, $97, $1d, $97, $20, $97, $18, $ff, $99, $00, $b1, $17, $b1, $18, $b1, $17, $cb, $18, $8b, $17
	.byte $89, $15, $97, $17, $97, $1e, $e5, $1a, $b1, $1c, $ff, $99, $00, $e5, $1d, $8b, $1c, $89, $1a, $97, $1c, $e5, $17, $b1
	.byte $13, $b1, $15, $b1, $17, $b1, $1a, $ff, $99, $00, $e5, $1c, $8b, $1a, $89, $18, $97, $1a, $ff, $99, $19, $ff, $99, $1a
	.byte $ff, $99, $19, $ff, $99, $1e, $ff, $99, $00, $ff, $99, $ff, $9b, $ff, $9b, $42
	.word @song5ch2loop
@song5ch3:
@song5ch3loop:
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $88
@song5ref908:
	.byte $30, $8b, $00, $a3
@song5ref912:
	.byte $30, $8b, $00, $89, $29
@song5ref917:
	.byte $8b, $00, $89, $30, $8b, $00, $89, $29, $8b, $00, $89, $30, $8b, $00, $a3, $25, $8b, $00, $a3, $25, $8b, $00, $89, $29
	.byte $8b, $00, $89
	.byte $41, $18
	.word @song5ref908
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song5ref917
	.byte $41, $20
	.word @song5ref912
	.byte $41, $18
	.word @song5ref908
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song5ref917
@song5ref969:
	.byte $30, $8b, $00, $a3, $30, $8b, $00, $a3, $30, $8b, $00, $a3, $25, $8b, $00, $a3, $25, $8b, $00, $a3, $30, $8b, $00, $a3
	.byte $30, $8b, $00, $a3, $30, $8b, $00, $a3, $30, $8b, $00, $a3, $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song5ref917
	.byte $41, $29
	.word @song5ref969
	.byte $41, $0f
	.word @song5ref917
	.byte $41, $20
	.word @song5ref912
	.byte $41, $18
	.word @song5ref908
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song5ref917
	.byte $41, $20
	.word @song5ref912
	.byte $41, $18
	.word @song5ref908
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song5ref917
	.byte $41, $29
	.word @song5ref969
	.byte $8b, $00, $89, $30, $8b, $00, $89, $29, $8b, $00, $89, $7f, $2e, $8b, $00, $a3, $7c, $2e, $8b, $00, $a3, $78, $2e, $8b
	.byte $00, $89, $7f, $29, $8b, $00, $89
@song5ref1081:
	.byte $74, $2e, $8b, $00
@song5ref1085:
	.byte $d7, $7f, $29, $8b, $00, $a3
@song5ref1091:
	.byte $2e, $8b, $00, $a3, $7c, $2e, $8b, $00, $89, $7f, $29, $8b, $00, $89, $78, $2e, $8b, $00, $89, $7f, $29, $8b, $00, $89
	.byte $74, $2e, $8b, $00, $f1, $7f, $29, $8b, $00, $89
	.byte $41, $0f
	.word @song5ref1091
	.byte $a3
	.byte $41, $1f
	.word @song5ref1081
	.byte $41, $14
	.word @song5ref1085
	.byte $a3
	.byte $41, $20
	.word @song5ref1081
	.byte $7f, $2a, $8b, $00, $89, $2e, $8b, $00, $a3, $7c, $2e, $8b, $00, $89, $7f, $2a, $8b, $00, $89, $78, $2e, $8b, $00, $a3
	.byte $74, $2e, $8b, $00, $a3, $7f, $e7
	.byte $41, $0e
	.word @song5ref676
	.byte $ff, $9b, $42
	.word @song5ch3loop
@song5ch4:
@song5ch4loop:
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $41, $0e
	.word @song5ref676
	.byte $42
	.word @song5ch4loop
