; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses release notes, you must set FAMISTUDIO_USE_RELEASE_NOTES = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Slide notes are used, you must set FAMISTUDIO_USE_SLIDE_NOTES = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_undertale=music_data_undertale
.endif

music_data_undertale:
	.byte 4
	.word @instruments
	.word @samples-4
; 00 : Once upon a time
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : Your Best Friend
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : Fallen Down
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 03 : Ruins
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_undertale
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env4,@env8,@env13,@env0 ; 00 : Lead
	.word @env12,@env8,@env11,@env3 ; 01 : Vibrate low vol
	.word @env2,@env8,@env9,@env0 ; 02 : Kicks
	.word @env5,@env8,@env9,@env15 ; 03 : Vibrate
	.word @env16,@env8,@env13,@env0 ; 04 : Echo
	.word @env7,@env8,@env9,@env0 ; 05 : Lead wavy
	.word @env6,@env8,@env9,@env10 ; 06 : Fade
	.word @env14,@env8,@env1,@env0 ; 07 : Flowey

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $c0,$c0,$c1,$00,$02
@env2:
	.byte $00,$c8,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env3:
	.byte $00,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$00,$01
@env4:
	.byte $0e,$cf,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$00,$0b,$c3,$05,$c2,$06,$c1,$06,$c1,$00,$14
@env5:
	.byte $00,$cf,$7f,$00,$02
@env6:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env7:
	.byte $0c,$c2,$c4,$c6,$c7,$c8,$c9,$ca,$02,$c9,$00,$05,$c7,$c5,$c4,$c3,$c2,$00,$10
@env8:
	.byte $c0,$7f,$00,$01
@env9:
	.byte $7f,$00,$00
@env10:
	.byte $00,$bd,$be,$bf,$be,$bf,$c0,$00,$06
@env11:
	.byte $c2,$7f,$00,$00
@env12:
	.byte $00,$ca,$c7,$c5,$c3,$00,$04
@env13:
	.byte $c1,$7f,$00,$00
@env14:
	.byte $00,$cf,$03,$c0,$00,$03
@env15:
	.byte $00,$c0,$c2,$c3,$c2,$c0,$be,$bd,$be,$00,$01
@env16:
	.byte $00,$cf,$06,$c0,$c0,$c8,$05,$c0,$c0,$c4,$04,$c0,$c0,$c2,$04,$c0,$c0,$c1,$00,$11

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $80
@song0ref2:
	.byte $25, $eb, $31, $eb, $48, $2c, $eb, $00, $eb, $48, $2a, $eb, $31, $eb, $48, $25, $eb, $00, $eb, $48, $25, $eb, $2a, $eb
	.byte $48, $31, $eb, $33, $eb, $48, $31, $eb, $2c, $eb, $48, $2a, $eb, $00, $eb, $48
	.byte $41, $1f
	.word @song0ref2
	.byte $d1, $4f, $01, $8a, $17, $8b, $18, $89
@song0ref53:
	.byte $48, $19, $a7, $00, $8b, $7a, $19, $99, $45, $97, $7f, $25, $99, $45, $99, $22, $99, $45, $97, $48, $20, $99, $45, $99
	.byte $1e, $b3, $1d, $b5, $1e, $b3, $48, $20, $b5, $45, $b3, $29, $d1, $28, $8b, $27, $89, $48, $25, $ff, $a3, $45, $b3, $48
	.byte $1b, $a7, $00, $8b, $7c, $1b, $8b, $00, $8b, $78, $1b, $8b, $00, $89, $7f, $25, $a7, $45, $8b, $22, $a7, $45, $89, $48
	.byte $20, $a7, $45, $8b, $1e, $b3, $20, $b5, $22, $b3, $48, $1d, $b5, $45, $b3, $20, $b7, $45, $b1, $48, $20, $b5, $1e, $b3
	.byte $1d, $b5, $1e, $b3
	.byte $41, $57
	.word @song0ref53
	.byte $48, $4f, $00, $8c
@song0ref160:
	.byte $31, $99, $76, $31, $99, $7f, $2a, $99, $76, $2a, $97, $7f, $2c, $99, $76, $2c, $99, $7f, $2a, $99, $76, $2a, $97, $48
	.byte $7f, $24, $99, $76, $24, $99, $7f, $2a, $99, $76, $2a, $97, $7f, $2c, $99, $76, $2c, $99, $7f, $2a, $99, $76, $2a, $97
	.byte $48, $7f, $23, $99, $76, $23, $99, $7f, $2a, $99, $76, $2a, $97, $7f, $2c, $99, $76, $2c, $99, $7f, $2f, $99, $76, $2f
	.byte $97, $48, $7f, $2e, $99, $76, $2e, $99, $7f, $2c, $99, $76, $2c, $97, $7f, $2a, $99, $76, $2a, $99, $7f, $25, $99, $76
	.byte $25, $97, $48, $7f, $4f, $00
	.byte $41, $40
	.word @song0ref160
	.byte $48, $7f, $31, $99, $76, $31, $99, $7f, $2a, $99, $76, $2a, $97, $7e, $2c, $99, $76, $2c, $99, $7e, $2a, $99, $76, $2a
	.byte $97, $48, $7d, $24, $99, $76, $24, $99, $7d, $2a, $99, $76, $2a, $97, $7c, $2c, $99, $75, $2c, $99, $7c, $2a, $99, $75
	.byte $2a, $97, $48, $7b, $23, $99, $75, $23, $99, $7b, $2a, $99, $75, $2a, $97, $7a, $2c, $99, $74, $2c, $99, $7a, $2f, $99
	.byte $74, $2f, $97, $48, $79, $2e, $99, $74, $2e, $99, $79, $2c, $99, $74, $2c, $97, $78, $2a, $99, $73, $2a, $99, $78, $25
	.byte $99, $73, $25, $97, $48, $77, $31, $99, $73, $31, $99, $77, $2a, $99, $73, $2a, $97, $76, $2c, $99, $72, $2c, $99, $76
	.byte $2a, $99, $72, $2a, $97, $48, $75, $24, $99, $72, $24, $99, $75, $2a, $99, $72, $2a, $97, $74, $2c, $99, $71, $2c, $99
	.byte $74, $2a, $99, $71, $2a, $97, $48, $73, $23, $99, $71, $23, $99, $73, $2a, $99, $71, $2a, $97, $72, $2c, $99, $00, $99
	.byte $2f, $99, $00, $97, $48, $71, $2e, $99, $00, $99, $2c, $99, $00, $b3, $7f, $d1, $44, $00
@song0ch1:
@song0ref452:
	.byte $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db
	.byte $41, $10
	.word @song0ref452
	.byte $82
@song0ref472:
	.byte $0b, $b5, $12, $b3, $14, $b5, $12, $b3, $0b
@song0ref481:
	.byte $b5, $12, $b3, $14, $b5, $12, $b3, $0a, $b5, $12, $b3, $14, $b5, $12, $b3, $09, $b5, $12, $b3, $14, $b5, $12, $b3, $08
	.byte $b5, $12, $b3, $14, $b5, $12, $b3, $0d
	.byte $41, $0f
	.word @song0ref481
	.byte $0f, $b5, $12, $b3, $11, $b5, $0d, $b3
	.byte $41, $29
	.word @song0ref472
	.byte $41, $0f
	.word @song0ref481
	.byte $0f, $b5, $12, $b3, $11, $b5, $0d, $b3, $00, $ff, $d9
	.byte $41, $10
	.word @song0ref452
@song0ref544:
	.byte $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $44, $00
@song0ch2:
	.byte $82
@song0ref562:
	.byte $1e, $ff, $d9, $22, $ff, $d9, $21, $ff, $d9, $20, $ff, $d9, $1e, $ff, $d9, $22, $ff, $d9, $21, $ff, $d9, $20, $ff, $a3
	.byte $00, $b3
	.byte $41, $1a
	.word @song0ref562
	.byte $17, $ff, $d9, $ff, $db
@song0ref596:
	.byte $16, $ff, $d9, $15, $ff, $d9, $14, $ff, $d9, $19, $ff, $d9, $16, $ff, $d9, $1b, $eb, $19, $eb, $17, $ff, $d9, $17, $ff
	.byte $d9
	.byte $41, $13
	.word @song0ref596
	.byte $2a, $ff, $d9, $2c, $ff, $d9, $23, $ff, $d9, $2a, $ff, $d9, $2a, $ff, $d9, $2c, $ff, $d9, $23, $ff, $d9, $2a, $ff, $d9
	.byte $00, $ff, $d9
	.byte $41, $0f
	.word @song0ref544
@song0ch3:
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $84
@song0ref662:
	.byte $04, $8b, $00, $a7, $10, $8b, $00, $a5, $0a, $8b, $00, $dd, $04, $8b, $00, $a7, $10, $8b, $00, $a5, $0a, $8b, $00, $dd
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $18
	.word @song0ref662
	.byte $41, $10
	.word @song0ref452
	.byte $44, $00
@song0ch4:
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $41, $10
	.word @song0ref452
	.byte $44, $00
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid)
@song1ref5:
	.byte $ff, $e7, $48, $ff, $e7, $48, $ff, $e7, $48, $ff, $e7, $48
	.byte $41, $08
	.word @song1ref5
	.byte $48
	.byte $41, $08
	.word @song1ref5
	.byte $42
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $7f, $8e
@song1ref30:
	.byte $21, $87, $00, $87, $78, $21, $87, $00, $87, $72, $21
@song1ref41:
	.byte $87, $00, $85, $7f, $25, $89, $00, $85, $78, $25, $87, $00, $87, $72, $25
@song1ref56:
	.byte $87, $00, $85, $7f, $1c, $89, $00, $85, $78, $1c, $87, $00, $87, $72, $1c
	.byte $41, $0f
	.word @song1ref41
	.byte $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
	.byte $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
	.byte $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
	.byte $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
@song1ref102:
	.byte $7f, $23, $87, $00, $87
@song1ref107:
	.byte $78, $23, $87, $00, $87, $72, $23
@song1ref114:
	.byte $87, $00, $85, $7f, $28, $89, $00, $85, $78, $28, $87, $00, $87, $72, $28
	.byte $41, $0c
	.word @song1ref56
	.byte $41, $0c
	.word @song1ref114
	.byte $87, $00, $85, $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
@song1ref145:
	.byte $7f, $1a, $87, $00, $87, $78, $1a, $87, $00, $87, $72, $1a, $87, $00, $85, $7f
	.byte $41, $0c
	.word @song1ref30
	.byte $7f, $23, $89, $00, $85
	.byte $41, $08
	.word @song1ref107
	.byte $7f, $34, $89, $00, $85, $78, $34, $87, $00, $87, $72, $34, $87, $00, $85, $7f
	.byte $41, $21
	.word @song1ref30
	.byte $41, $0f
	.word @song1ref41
	.byte $41, $0c
	.word @song1ref145
	.byte $41, $0c
	.word @song1ref102
@song1ref200:
	.byte $7f, $20, $87, $00, $87, $78, $20, $87, $00, $87, $72, $20, $87, $00, $85, $7f, $2c, $89, $00, $85, $78, $2c, $87, $00
	.byte $87, $72, $2c, $87, $00, $85
	.byte $41, $0c
	.word @song1ref145
	.byte $7f, $1e, $87, $00, $87, $78, $1e, $87, $00, $87, $72, $1e, $87, $00, $85, $7f, $1c, $87, $00, $87, $78, $1c, $87, $00
	.byte $87, $72, $1c, $87, $00, $85
	.byte $41, $0c
	.word @song1ref200
	.byte $7f
	.byte $41, $0c
	.word @song1ref30
	.byte $7f, $9d, $2a, $81, $2a, $81, $2c, $2c, $81, $2d, $83, $2d, $81, $2d, $81, $2d, $81, $2d, $83, $2d, $2d, $81, $00, $e1
	.byte $42
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
@song1ref298:
	.byte $ff, $e7, $ff, $e7, $ff, $e7, $ff, $e7, $80
@song1ref307:
	.byte $3d, $8d, $00, $a7, $3d, $9b, $3e, $99, $40, $4c, $9b, $00, $99, $3d, $9b, $00, $99, $3e, $8d, $00, $a7, $3e, $9b, $40
	.byte $4c, $99, $3b, $9b, $00, $99, $34, $9b, $00, $99
	.byte $41, $0c
	.word @song1ref307
	.byte $40, $51, $9b, $00, $99, $40, $4e, $e3, $3e, $83, $3f, $85, $40, $4c, $9b, $00, $d3
	.byte $41, $20
	.word @song1ref307
	.byte $41, $08
	.word @song1ref307
	.byte $3b, $9b, $00, $99, $38, $9b, $00, $99, $39, $d5, $40, $4f, $85, $40, $50, $83, $40, $51, $9b, $00, $e1, $42
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $41, $08
	.word @song1ref298
	.byte $41, $08
	.word @song1ref298
	.byte $41, $08
	.word @song1ref298
	.byte $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $41, $08
	.word @song1ref298
	.byte $41, $08
	.word @song1ref298
	.byte $41, $08
	.word @song1ref298
	.byte $42
	.word @song1ch4loop
@song2ch0:
@song2ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song2ref6:
	.byte $2b, $9d, $26, $9d, $2b, $9d, $26, $9d, $2b, $9d, $26, $9d, $48, $2b, $9d, $26, $9d, $2b, $9d, $26, $9d, $2b, $9d, $26
	.byte $9d, $48, $24, $9d, $22, $9d, $26, $9d, $00, $9d, $22, $9d, $24, $9d, $48, $29, $9d, $28, $9d, $29, $9d, $2b, $9d, $28
	.byte $9d, $24, $9d, $48, $2b, $9d, $24, $9d, $2b, $9d, $24, $9d, $2b, $9d, $24, $9d, $48, $2b, $9d, $23, $9d, $2b, $9d, $24
	.byte $9d, $2c, $9d, $00, $9d, $48, $2b, $9d, $27, $9d, $2b, $9d, $27, $9d, $29, $9d, $2b, $9d, $48, $29, $9d, $00, $9d, $27
	.byte $9d, $00, $9d, $26, $9d, $00, $9d, $48
	.byte $41, $60
	.word @song2ref6
	.byte $48
	.byte $41, $60
	.word @song2ref6
	.byte $48
	.byte $41, $60
	.word @song2ref6
	.byte $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $82
@song2ref126:
	.byte $1b, $9d, $1f, $9d, $22, $9d, $1f, $9d, $22, $9d, $1f, $9d, $1b, $9d, $1f, $9d, $22, $9d, $1f, $9d, $22, $9d, $1f, $9d
	.byte $18, $9d, $1c, $9d, $1f, $9d, $1c, $9d, $1f, $9d, $1c, $9d, $18, $9d, $1c, $9d, $1f, $9d, $1c, $9d, $1f, $9d, $1c, $9d
	.byte $14, $9d, $18, $9d, $1b, $9d, $18, $9d, $1b, $9d, $18, $9d, $14, $9d, $17, $9d, $1b, $9d, $17, $9d, $1b, $9d, $17, $9d
	.byte $1b, $9d, $1f, $9d, $22, $9d, $1f, $9d, $22, $9d, $1f, $9d, $1a, $9d, $1d, $9d, $22, $9d, $1d, $9d, $22, $9d, $1d, $9d
	.byte $41, $60
	.word @song2ref126
	.byte $41, $60
	.word @song2ref126
	.byte $41, $60
	.word @song2ref126
	.byte $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
@song2ref235:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $86
@song2ref267:
	.byte $26, $bd, $27, $dd, $1b, $c5, $50, $ea, $27, $2e, $95, $22, $fd, $26, $bd, $24, $ff, $8d, $50, $07, $30, $2b, $ad, $1f
	.byte $ff, $bd, $20, $bd, $50, $f4, $2c, $33, $9d, $27, $dd, $bf, $50, $07, $33, $2f, $9d, $23, $dd, $22, $ff, $bd, $22, $bd
	.byte $20, $bd
	.byte $41, $1f
	.word @song2ref267
	.byte $1b, $ff, $bd, $ff, $00, $bd, $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $41, $1f
	.word @song2ref235
	.byte $bf
	.byte $41, $1f
	.word @song2ref235
	.byte $bf, $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $41, $1f
	.word @song2ref235
	.byte $bf
	.byte $41, $1f
	.word @song2ref235
	.byte $bf, $42
	.word @song2ch4loop
@song3ch0:
@song3ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $9b, $48, $ff, $9b, $48, $ff, $9b, $48, $78, $b3, $88
	.byte $2a, $97, $2b, $97, $2a, $81, $2b, $83, $2a, $81, $2b, $83, $2a, $83, $26, $97, $48
@song3ref34:
	.byte $28, $cb, $2d, $b1, $30, $97, $48, $2d, $b1, $2f, $97, $30, $97, $32, $97, $2f, $97, $48, $30, $cb, $2f, $b1, $2d, $8b
	.byte $2b, $89, $48, $2a, $b1, $30, $97, $32, $97, $34, $97, $36, $97, $48, $30, $cb, $2f, $b1, $28, $97, $48, $2d, $b1, $2b
	.byte $b1, $2a, $b1, $48, $2b, $97, $2a, $97, $28, $97, $26, $b1, $2d, $97, $48, $28, $b1, $00, $97, $23, $97, $24, $97, $23
	.byte $97, $48, $26, $e5, $00, $b1, $48, $b3, $36, $97, $37, $97, $36, $97, $37, $97, $48, $36, $cb, $39, $cb, $48, $34, $cb
	.byte $2f, $97, $30, $97, $2f, $97, $48, $32, $e5, $00, $b1, $48, $cd, $2f, $97, $30, $97, $2f, $97, $48, $32, $e5, $00, $b1
	.byte $48, $ff, $9b, $48, $7f, $4f, $02
	.byte $41, $6c
	.word @song3ref34
	.byte $48, $4f, $02
	.byte $41, $55
	.word @song3ref34
	.byte $23, $97, $24, $97, $23, $97, $48, $26, $ff, $99, $48, $00, $cb, $23, $97, $25, $97, $23, $97, $48, $26, $ff, $99, $48
	.byte $2c, $cb, $2b, $97, $29, $97, $2c, $97, $48, $24, $ff, $99, $48, $00, $b1, $23, $b1, $24, $b1, $48, $23, $cb, $24, $8b
	.byte $23, $89, $21, $97, $23, $97, $48, $2a, $e5, $26, $b1, $48, $28, $ff, $99, $48, $00, $e5, $29, $8b, $28, $89, $26, $97
	.byte $48, $28, $e5, $23, $b1, $48, $1f, $b1, $21, $b1, $23, $b1, $48, $26, $ff, $99, $48, $00, $e5, $28, $8b, $26, $89, $24
	.byte $97, $48, $26, $ff, $99, $48, $25, $ff, $99, $48, $26, $ff, $99, $48, $25, $ff, $99, $48, $2a, $ff, $99, $48, $74, $15
	.byte $b1, $00, $e5, $48, $10, $97, $17, $97, $13, $b1, $12, $97, $13, $97, $48, $15, $b1, $00, $e5, $42
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $78, $88
@song3ref315:
	.byte $15, $97, $1c, $97, $18, $b1, $17, $97, $18, $97, $1a, $b1, $00, $cb, $13, $97
	.byte $41, $0d
	.word @song3ref315
	.byte $e5
	.byte $41, $10
	.word @song3ref315
	.byte $41, $0d
	.word @song3ref315
	.byte $e5
	.byte $41, $10
	.word @song3ref315
	.byte $41, $0d
	.word @song3ref315
@song3ref348:
	.byte $97, $0e, $97, $13, $97, $10
@song3ref354:
	.byte $97, $15, $97, $1c, $97, $18, $b1, $17, $97, $18, $97, $1a, $b1, $0e, $97, $15, $97, $18, $97, $17
	.byte $41, $0d
	.word @song3ref354
	.byte $12, $97, $0e, $97, $10, $97, $12
	.byte $41, $0d
	.word @song3ref354
	.byte $00, $e5, $21, $97, $28, $97, $24, $b1, $23, $97, $24, $97, $26, $b1, $00, $e5
@song3ref403:
	.byte $7f
@song3ref404:
	.byte $09, $97, $10, $97, $0c, $b1, $0b, $97, $0c, $97, $0e, $b1, $00, $97, $09, $97, $07, $97, $13, $97, $09, $97, $10, $97
	.byte $0c, $b1, $0e, $97, $10, $97, $12, $b1, $00, $b1, $12, $97, $0e, $97
	.byte $41, $22
	.word @song3ref404
	.byte $09, $97, $0e, $97, $78
	.byte $41, $0d
	.word @song3ref315
	.byte $41, $13
	.word @song3ref348
	.byte $00
	.byte $41, $13
	.word @song3ref348
	.byte $00, $e5, $ff, $9b, $ff, $9b
	.byte $41, $26
	.word @song3ref403
	.byte $41, $22
	.word @song3ref404
	.byte $09, $97, $0e, $97, $78
	.byte $41, $0d
	.word @song3ref315
	.byte $41, $13
	.word @song3ref348
	.byte $00, $97, $0e, $97, $13, $97, $10, $97, $7f, $0b, $97, $12, $97, $0e, $b1, $0b, $97, $12, $97, $0b, $97, $12, $97, $17
	.byte $b1, $00, $b1, $0a, $97, $11, $97, $0e, $b1, $0a, $97, $11, $97, $0a, $97, $11, $97, $14, $b1, $13, $97, $11, $97, $09
	.byte $97, $10, $97, $0c, $b1, $09, $97, $10, $97, $09, $97, $10, $97, $15, $b1, $10, $b1, $07, $97, $0b, $97, $13, $b1, $0e
	.byte $b1, $0e, $b1, $10, $b1, $12, $b1, $05, $97, $10, $97, $0c, $cb, $10, $97, $05, $b1, $10, $b1, $15, $b1, $0b, $97, $0e
	.byte $97, $0b, $cb, $0e, $97, $0b, $b1, $0e, $b1, $10, $b1, $13, $ff, $99, $00, $ff, $99
@song3ref596:
	.byte $1c, $97, $1f, $97, $23, $97, $1f, $97, $22, $97, $1e, $97, $1c, $97, $1f, $97, $23, $97, $1f, $97, $22, $97, $1e, $97
	.byte $41, $18
	.word @song3ref596
	.byte $1c, $97, $23, $97, $26, $97, $23, $97, $25, $97, $21, $97, $1c, $97, $23, $97, $26, $97, $23, $97, $25, $97, $21, $97
	.byte $00, $ff, $99, $ff, $9b, $42
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
@song3ref656:
	.byte $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $ff, $9b, $86, $1c, $cb, $21, $b1, $24, $97, $21, $b1, $23, $97, $24, $97, $26, $97, $23, $97, $24, $cb, $23, $b1, $21
	.byte $8b, $1f, $89, $1e, $b1, $24, $97, $26, $97, $28, $97, $2a, $97, $24, $cb, $23, $b1, $1c, $97, $21, $b1, $1f, $b1, $1e
	.byte $b1, $1f, $97, $1e, $97, $1c, $97, $1a, $b1, $21, $97, $1c, $b1, $00, $97, $17, $97, $18, $97, $17, $97, $1a, $e5, $00
	.byte $b1, $ff, $9b, $ff, $9b, $cd, $17, $97, $18, $97, $17, $97, $1a, $ff, $99, $00, $cb, $17, $97, $19, $97, $17, $97, $1a
	.byte $ff, $99, $20, $cb, $1f, $97, $1d, $97, $20, $97, $18, $ff, $99, $00, $b1, $17, $b1, $18, $b1, $17, $cb, $18, $8b, $17
	.byte $89, $15, $97, $17, $97, $1e, $e5, $1a, $b1, $1c, $ff, $99, $00, $e5, $1d, $8b, $1c, $89, $1a, $97, $1c, $e5, $17, $b1
	.byte $13, $b1, $15, $b1, $17, $b1, $1a, $ff, $99, $00, $e5, $1c, $8b, $1a, $89, $18, $97, $1a, $ff, $99, $18, $ff, $99, $1a
	.byte $ff, $99, $18, $ff, $99, $1e, $ff, $99, $00, $ff, $99, $ff, $9b, $ff, $9b, $42
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $ff, $9b, $84
@song3ref888:
	.byte $30, $8b, $00, $a3
@song3ref892:
	.byte $30, $8b, $00, $89, $29
@song3ref897:
	.byte $8b, $00, $89, $30, $8b, $00, $89, $29, $8b, $00, $89, $30, $8b, $00, $a3, $25, $8b, $00, $a3, $25, $8b, $00, $89, $29
	.byte $8b, $00, $89
	.byte $41, $18
	.word @song3ref888
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song3ref897
	.byte $41, $20
	.word @song3ref892
	.byte $41, $18
	.word @song3ref888
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song3ref897
@song3ref949:
	.byte $30, $8b, $00, $a3, $30, $8b, $00, $a3, $30, $8b, $00, $a3, $25, $8b, $00, $a3, $25, $8b, $00, $a3, $30, $8b, $00, $a3
	.byte $30, $8b, $00, $a3, $30, $8b, $00, $a3, $30, $8b, $00, $a3, $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song3ref897
	.byte $41, $29
	.word @song3ref949
	.byte $41, $0f
	.word @song3ref897
	.byte $41, $20
	.word @song3ref892
	.byte $41, $18
	.word @song3ref888
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song3ref897
	.byte $41, $20
	.word @song3ref892
	.byte $41, $18
	.word @song3ref888
	.byte $30, $8b, $00, $89, $30
	.byte $41, $0f
	.word @song3ref897
	.byte $41, $29
	.word @song3ref949
	.byte $8b, $00, $89, $30, $8b, $00, $89, $29, $8b, $00, $89, $7f, $2e, $8b, $00, $a3, $7c, $2e, $8b, $00, $a3, $78, $2e, $8b
	.byte $00, $89, $7f, $29, $8b, $00, $89
@song3ref1061:
	.byte $74, $2e, $8b, $00
@song3ref1065:
	.byte $d7, $7f, $29, $8b, $00, $a3
@song3ref1071:
	.byte $2e, $8b, $00, $a3, $7c, $2e, $8b, $00, $89, $7f, $29, $8b, $00, $89, $78, $2e, $8b, $00, $89, $7f, $29, $8b, $00, $89
	.byte $74, $2e, $8b, $00, $f1, $7f, $29, $8b, $00, $89
	.byte $41, $0f
	.word @song3ref1071
	.byte $a3
	.byte $41, $1f
	.word @song3ref1061
	.byte $41, $14
	.word @song3ref1065
	.byte $a3
	.byte $41, $20
	.word @song3ref1061
	.byte $7f, $2a, $8b, $00, $89, $2e, $8b, $00, $a3, $7c, $2e, $8b, $00, $89, $7f, $2a, $8b, $00, $89, $78, $2e, $8b, $00, $a3
	.byte $74, $2e, $8b, $00, $a3, $7f, $e7
	.byte $41, $0e
	.word @song3ref656
	.byte $ff, $9b, $42
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $41, $0e
	.word @song3ref656
	.byte $42
	.word @song3ch4loop
