; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Project uses release notes, you must set FAMISTUDIO_USE_RELEASE_NOTES = 1.
; Volume track is used, you must set FAMISTUDIO_USE_VOLUME_TRACK = 1.
; Duty Cycle effect is used, you must set FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1.

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_undertale=music_data_undertale
.endif

music_data_undertale:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Once upon a time
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_undertale
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env10,@env6,@env9,@env2 ; 00 : Vibrate low vol
	.word @env3,@env6,@env11,@env0 ; 01 : Lead
	.word @env5,@env6,@env7,@env0 ; 02 : Lead wavy
	.word @env4,@env6,@env7,@env8 ; 03 : Fade
	.word @env1,@env6,@env7,@env0 ; 04 : Kicks

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$c8,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
@env2:
	.byte $00,$c0,$c1,$c2,$c1,$c0,$bf,$be,$bf,$00,$01
@env3:
	.byte $0e,$cf,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$00,$0b,$c3,$05,$c2,$06,$c1,$06,$c1,$00,$14
@env4:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env5:
	.byte $0c,$c2,$c4,$c6,$c7,$c8,$c9,$ca,$02,$c9,$00,$05,$c7,$c5,$c4,$c3,$c2,$00,$10
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $00,$bd,$be,$bf,$be,$bf,$c0,$00,$06
@env9:
	.byte $c2,$7f,$00,$00
@env10:
	.byte $00,$ca,$c7,$c5,$c3,$00,$04
@env11:
	.byte $c1,$7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $82
@song0ref6:
	.byte $25, $eb, $31, $eb, $48, $2c, $eb, $00, $eb, $48, $2a, $eb, $31, $eb, $48, $25, $eb, $00, $eb, $48, $25, $eb, $2a, $eb
	.byte $48, $31, $eb, $33, $eb, $48, $31, $eb, $2c, $eb, $48, $2a, $eb, $00, $eb, $48
	.byte $41, $1f
	.word @song0ref6
	.byte $d1, $7f, $4f, $01, $84, $17, $8b, $18, $89
@song0ref58:
	.byte $48, $19, $a7, $00, $8b, $7a, $19, $99, $45, $97, $7f, $25, $99, $45, $99, $22, $99, $45, $97, $48, $20, $99, $45, $99
	.byte $1e, $b3, $1d, $b5, $1e, $b3, $48, $20, $b5, $45, $b3, $29, $d1, $28, $8b, $27, $89, $48, $25, $ff, $a3, $45, $b3, $48
	.byte $1b, $a7, $00, $8b, $7c, $1b, $8b, $00, $8b, $78, $1b, $8b, $00, $89, $7f, $25, $a7, $45, $8b, $22, $a7, $45, $89, $48
	.byte $20, $a7, $45, $8b, $1e, $b3, $20, $b5, $22, $b3, $48, $1d, $b5, $45, $b3, $20, $b7, $45, $b1, $48, $20, $b5, $1e, $b3
	.byte $1d, $b5, $1e, $b3
	.byte $41, $57
	.word @song0ref58
	.byte $48, $4f, $00, $86
@song0ref165:
	.byte $31, $99, $76, $31, $99, $7f, $2a, $99, $76, $2a, $97, $7f, $2c, $99, $76, $2c, $99, $7f, $2a, $99, $76, $2a, $97, $48
	.byte $7f, $24, $99, $76, $24, $99, $7f, $2a, $99, $76, $2a, $97, $7f, $2c, $99, $76, $2c, $99, $7f, $2a, $99, $76, $2a, $97
	.byte $48, $7f, $23, $99, $76, $23, $99, $7f, $2a, $99, $76, $2a, $97, $7f, $2c, $99, $76, $2c, $99, $7f, $2f, $99, $76, $2f
	.byte $97, $48, $7f, $2e, $99, $76, $2e, $99, $7f, $2c, $99, $76, $2c, $97, $7f, $2a, $99, $76, $2a, $99, $7f, $25, $99, $76
	.byte $25, $97, $48, $7f, $4f, $00
	.byte $41, $40
	.word @song0ref165
	.byte $48, $7f, $31, $99, $76, $31, $99, $7f, $2a, $99, $76, $2a, $97, $7e, $2c, $99, $76, $2c, $99, $7e, $2a, $99, $76, $2a
	.byte $97, $48, $7d, $24, $99, $76, $24, $99, $7d, $2a, $99, $76, $2a, $97, $7c, $2c, $99, $75, $2c, $99, $7c, $2a, $99, $75
	.byte $2a, $97, $48, $7b, $23, $99, $75, $23, $99, $7b, $2a, $99, $75, $2a, $97, $7a, $2c, $99, $74, $2c, $99, $7a, $2f, $99
	.byte $74, $2f, $97, $48, $79, $2e, $99, $74, $2e, $99, $79, $2c, $99, $74, $2c, $97, $78, $2a, $99, $73, $2a, $99, $78, $25
	.byte $99, $73, $25, $97, $48, $77, $31, $99, $73, $31, $99, $77, $2a, $99, $73, $2a, $97, $76, $2c, $99, $72, $2c, $99, $76
	.byte $2a, $99, $72, $2a, $97, $48, $75, $24, $99, $72, $24, $99, $75, $2a, $99, $72, $2a, $97, $74, $2c, $99, $71, $2c, $99
	.byte $74, $2a, $99, $71, $2a, $97, $48, $73, $23, $99, $71, $23, $99, $73, $2a, $99, $71, $2a, $97, $72, $2c, $99, $00, $99
	.byte $2f, $99, $00, $97, $48, $71, $2e, $99, $00, $99, $2c, $99, $00, $b3, $7f, $d1, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref458:
	.byte $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db
	.byte $ff, $db, $ff, $db, $ff, $db, $ff, $db, $80
@song0ref491:
	.byte $0b, $b5, $12, $b3, $14, $b5, $12, $b3, $0b, $b5, $12, $b3, $14, $b5, $12, $b3, $0a, $b5, $12, $b3, $14, $b5, $12, $b3
	.byte $09, $b5, $12, $b3, $14, $b5, $12, $b3, $08, $b5, $12, $b3, $14, $b5, $12, $b3, $0d, $b5, $12, $b3, $14, $b5, $12, $b3
	.byte $0a, $b5, $12, $b3, $14, $b5, $12, $b3, $0f, $b5, $12, $b3, $11, $b5, $0d, $b3
	.byte $41, $40
	.word @song0ref491
	.byte $00, $ff, $d9
	.byte $41, $1e
	.word @song0ref458
	.byte $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref569:
	.byte $1e, $ff, $d9, $22, $ff, $d9, $21, $ff, $d9, $20, $ff, $d9, $1e, $ff, $d9, $22, $ff, $d9, $21, $ff, $d9, $20, $ff, $a3
	.byte $00, $b3
	.byte $41, $1a
	.word @song0ref569
	.byte $17, $ff, $d9, $ff, $db
@song0ref603:
	.byte $16, $ff, $d9, $15, $ff, $d9, $14, $ff, $d9, $19, $ff, $d9, $16, $ff, $d9, $1b, $eb, $19, $eb, $17, $ff, $d9, $17, $ff
	.byte $d9
	.byte $41, $13
	.word @song0ref603
	.byte $2a, $ff, $d9, $2c, $ff, $d9, $23, $ff, $d9, $2a, $ff, $d9, $2a, $ff, $d9, $2c, $ff, $d9, $23, $ff, $d9, $2a, $ff, $d9
	.byte $00, $ff, $d9, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $42
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $41, $20
	.word @song0ref458
	.byte $88
@song0ref680:
	.byte $04, $8b, $00, $a7, $10, $8b, $00, $a5, $0a, $8b, $00, $dd, $04, $8b, $00, $a7, $10, $8b, $00, $a5, $0a, $8b, $00, $dd
	.byte $41, $18
	.word @song0ref680
	.byte $41, $18
	.word @song0ref680
	.byte $41, $18
	.word @song0ref680
	.byte $41, $18
	.word @song0ref680
	.byte $41, $18
	.word @song0ref680
	.byte $41, $18
	.word @song0ref680
	.byte $41, $18
	.word @song0ref680
	.byte $41, $18
	.word @song0ref680
	.byte $41, $18
	.word @song0ref680
	.byte $41, $18
	.word @song0ref680
	.byte $41, $18
	.word @song0ref680
	.byte $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $42
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $41, $20
	.word @song0ref458
	.byte $41, $20
	.word @song0ref458
	.byte $41, $20
	.word @song0ref458
	.byte $42
	.word @song0ch4loop
